before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: ' xamehQRWs1e8tPHaP624+9mxpVOqCP/P/RSOJpAdwlwdhSdbHMwuRKW+ZkrJTxZSNb51Yx5POKrrZVRbE2UJ7+67UHobC2hjputjw3psxz8lMW1dCdRpFhfgXotdeo3pcdjtFwG4e+LpKN3xApcHHAqGvJIuOPwdKaCmPEN1HHg='
    - MASSAH_RUNNER=browserstack
    - MASSAH_PROJECT="$TRAVIS_REPO_SLUG"
    - MASSAH_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
    - BROWSERSTACK_LOCAL_WAIT=20000
  matrix:
    - MASSAH_RUNNER=vanilla MASSAH_BROWSER=Firefox
    - MASSAH_BROWSER=IE MASSAH_OS=Windows MASSAH_OS_VERSION=XP MASSAH_BROWSER_VERSION=6
    - MASSAH_BROWSER=Safari MASSAH_OS="OS X" MASSAH_OS_VERSION=Mavericks
#    - MASSAH_BROWSER=Chrome MASSAH_OS=Windows
#    - MASSAH_BROWSER=Safari MASSAH_OS=Windows
#    - MASSAH_BROWSER=Opera MASSAH_OS=Windows
#    - MASSAH_BROWSER=Chrome MASSAH_OS="OS X" MASSAH_OS_VERSION=Mavericks
